name: parttec
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.0
  http: ^1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  qr_code_scanner: ^1.0.1
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.2   # ✅ آخر نسخة متوافقة مع Dart 3.3
  fl_chart: ^0.68.0
  file_picker: ^8.0.0
  firebase_core: ^2.32.0       # ✅ متوافقة مع Dart 3.3
  firebase_messaging: ^14.7.10 # ✅ متوافقة مع Dart 3.3
  flutter_local_notifications: 18.0.1 # ✅ نزّلنا النسخة لحل مشكلة SDK

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
